# Generated by Django 3.2.9 on 2021-12-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211203_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, max_length=254),
        ),
    ]
