# Generated by Django 3.2.9 on 2021-12-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.URLField(blank=True, default='https://depositphotos.com/247872612/stock-illustration-no-image-available-icon-vector.html', max_length=254),
        ),
    ]
