# Generated by Django 3.2.9 on 2021-12-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_listing_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='url',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
