# Generated by Django 3.2.9 on 2021-12-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_watchlist_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='content',
        ),
    ]
