# Generated by Django 3.2.9 on 2021-12-05 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_auto_20211205_1055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
