# Generated by Django 3.2.9 on 2021-12-05 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_user_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
    ]
